name: Android Build
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
 
      # Instala o Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
 
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
 
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
 
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ProfessorNotasApp
          path: app/build/outputs/apk/debug/app-debug.apk
 
