name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        run: |
          sudo mkdir -p $ANDROID_HOME/cmdline-tools
          sudo chown $USER $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk.zip -d latest
          rm sdk.zip
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Give permissions to gradlew and wrapper
        run: |
          chmod +x gradlew
          chmod +rwx gradle/wrapper/gradle-wrapper.jar

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
